#!/usr/bin/env bash

CLR_ESC=$'\033['
NOCOLOR=$'\033[0m'

DEFAULT=$'37m'

# All these variables has a function with the same name, but in lower case.
RED=$'31m'              # set red foreground
GREEN=$'32m'            # set green foreground
YELLOW=$'33m'           # set brown foreground
BLUE=$'34m'             # set blue foreground
MAGENTA=$'35m'          # set magenta foreground
CYAN=$'36m'             # set cyan foreground
WHITE=$'37m'            # set white foreground
GRAY=$'90m'             # set gray foreground

function echoColorText () {
  echo $CLR_ESC$3"$2$1"${NOCOLOR}
}

if [ -d "./node_modules" ]; then
    echoColorText 'Updating Node Modules' 'INFO: ' $YELLOW
    npm update
else
    echoColorText 'Installing Node Modules' 'INFO: ' $YELLOW
    npm install
fi

echoColorText 'Compiling theme assets' 'INFO: ' $BLUE
gulp compile

